name: quality-check-dagster-and-dbt

on:
  schedule:
    - cron: "0 0 * * 0"

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - dagster_university/dagster_and_dbt/**

jobs:
  check:
    uses: ./.github/workflows/template-quality-check.yml
    with:
      working_directory: ./dagster_university/dagster_and_dbt