name: quality-check-dagster-essentials

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - dagster_university/dagster_essentials/**

jobs:
  check:
    uses: ./.github/workflows/template-quality-check.yml
    with:
      working_directory: ./dagster_university/dagster_essentials