name: Dagster University Ruff

on:
  push:
    branches:
      - "main"
    paths:
      - dagster_university/**
      - dagster_university_tests/**
  pull_request:
    branches:
      - "main"
    paths:
      - dagster_university/**
      - dagster_university_tests/**

jobs:
  build:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
